name: Develop Branch CI

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**/*.md'


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.PG_DB_NAME }}
          POSTGRES_USER: ${{ secrets.PG_DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}

      redis:
        image: redis:7
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
      - name: 리포지토리 checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 빌드 및 테스트
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build test
